// Copyright 2026, the Flutter authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.

/// Pins a new version of the prebuilt `cwebp` binaries.
///
/// Usage, from the `packages/dash_media_convert` directory:
///
/// ```bash
/// dart run tool/pin_cwebp.dart 1.6.0
/// ```
library;

import 'dart:io';

import 'package:crypto/crypto.dart';
import 'package:dash_media_convert/src/cwebp.dart';
import 'package:dash_media_convert/src/cwebp_pins.dart';
import 'package:http/http.dart' as http;
import 'package:path/path.dart' as p;

/// The fingerprint of the key that signs libwebp releases,
/// `WebP release signing key <webp-discuss@webmproject.org>`.
const String _signingKeyFingerprint =
    '6B0E6B70976DE303EDF2F601F9C3D6BDB8232B5D';

void main(List<String> arguments) async {
  final version = arguments.singleOrNull;
  if (version == null || !RegExp(r'^\d+\.\d+\.\d+$').hasMatch(version)) {
    stderr.writeln('Usage: dart run tool/pin_cwebp.dart <version>');
    exit(64);
  }

  final pins = <String, CwebpPin>{};
  final tempDirectory = Directory.systemTemp.createTempSync('pin_cwebp');
  try {
    for (final MapEntry(key: platform, value: currentPin)
        in cwebpPins.entries) {
      final archiveName = currentPin.archiveName.replaceFirst(
        pinnedCwebpVersion,
        version,
      );
      final unhashedPin = CwebpPin(
        archiveName: archiveName,
        archiveSha256: '',
        binarySha256: '',
      );
      print('Downloading $archiveName...');

      final archiveUrl = unhashedPin.archiveUrl;
      final archiveBytes = await http.readBytes(archiveUrl);
      final archivePath = p.join(tempDirectory.path, archiveName);
      File(archivePath).writeAsBytesSync(archiveBytes);
      final signaturePath = '$archivePath.asc';
      File(signaturePath)
          .writeAsBytesSync(await http.readBytes(Uri.parse('$archiveUrl.asc')));
      await _verifySignature(archivePath, signaturePath);

      pins[platform] = CwebpPin(
        archiveName: archiveName,
        archiveSha256: sha256.convert(archiveBytes).toString(),
        binarySha256: sha256
            .convert(unhashedPin.extractBinary(archiveBytes))
            .toString(),
      );
    }
  } finally {
    tempDirectory.deleteSync(recursive: true);
  }

  final pinsFile = File(p.join('lib', 'src', 'cwebp_pins.dart'))
    ..writeAsStringSync(_pinsSource(version, pins));
  await Process.run(Platform.resolvedExecutable, ['format', pinsFile.path]);

  print(
    '\nPinned cwebp $version in ${pinsFile.path}.\n'
    'Review the changes, then build a site to verify the new version.',
  );
}

Future<void> _verifySignature(String filePath, String signaturePath) async {
  final ProcessResult result;
  try {
    result = await Process.run('gpg', [
      '--status-fd',
      '1',
      '--verify',
      signaturePath,
      filePath,
    ]);
  } on ProcessException {
    throw StateError('gpg is required to verify the release signatures.');
  }

  // Check the signing key rather than trusting any key in the keyring.
  final validSignature = RegExp(
    r'^\[GNUPG:\] VALIDSIG (\S+)',
    multiLine: true,
  ).firstMatch(result.stdout as String)?.group(1);
  if (result.exitCode != 0 || validSignature != _signingKeyFingerprint) {
    throw StateError(
      'Failed to verify the signature of ${p.basename(filePath)}.\n'
      'If the signing key isn\'t in your keyring, import it with:\n'
      '  gpg --keyserver keyserver.ubuntu.com '
      '--recv-keys $_signingKeyFingerprint\n'
      '${result.stderr}',
    );
  }
}

String _pinsSource(String version, Map<String, CwebpPin> pins) {
  final buffer = StringBuffer('''
// Copyright 2026, the Flutter authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.

// Generated by `dart run tool/pin_cwebp.dart <version>`,
// run from the `packages/dash_media_convert` directory.

import 'cwebp.dart';

/// The version of libwebp whose prebuilt `cwebp` binary is used.
const String pinnedCwebpVersion = '$version';

/// The prebuilt `cwebp` downloads for [pinnedCwebpVersion],
/// keyed by `'<os>_<arch>'` as returned by [currentCwebpPlatform].
const Map<String, CwebpPin> cwebpPins = {
''');
  for (final MapEntry(key: platform, value: pin) in pins.entries) {
    buffer
      ..writeln("  '$platform': CwebpPin(")
      ..writeln("    archiveName: '${pin.archiveName}',")
      ..writeln("    archiveSha256: '${pin.archiveSha256}',")
      ..writeln("    binarySha256: '${pin.binarySha256}',")
      ..writeln('  ),');
  }
  buffer.writeln('};');
  return buffer.toString();
}
