name: optimistic_state
description: Example for optimistic_state cookbook recipe

resolution: workspace
environment:
  sdk: ^3.13.0-0

dependencies:
  flutter:
    sdk: flutter
  material_ui: ^1.5.0

flutter:
  uses-material-design: true
