# See Dependabot documentation for all configuration options:
# https://docs.github.com/code-security/reference/supply-chain-security/dependabot-options-reference

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      github-actions:
        patterns:
          - "*"
    labels:
      - "auto.dependencies"
      - "auto.github-action"

  - package-ecosystem: "pub"
    versioning-strategy: "increase-if-necessary"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "auto.dependencies"

  - package-ecosystem: "pub"
    versioning-strategy: "increase-if-necessary"
    directory: "/examples"
    schedule:
      interval: "weekly"
    groups:
      example-dependencies:
        patterns:
          - "*"
    labels:
      - "auto.code-examples"
