name: flutter_websites
description: >-
  Pub workspace for Flutter websites and related tooling.
publish_to: none

environment:
  sdk: ^3.11.0

workspace:
  - packages/analysis_defaults
  - packages/excerpter
  - sites/docs
  - tool/dash_site
