// Copyright 2026, the Flutter authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.

/// Generated by flutter_website|stylesHashBuilder. Do not edit.
///
/// This hash is used to cache bust the CSS file.
/// It is generated from the SCSS source files and
/// is used to ensure that the CSS file is re-generated
/// when the SCSS source files change.
///
/// The hash is generated using the SHA-256 hash function
/// and is encoded using Base64 URL encoding.
library;

// dart format off

/// The generated hash of the SCSS source files.
const generatedStylesHash = '';
