// Copyright 2026, the Flutter authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.

import 'dart:io' show File;

import 'package:code_builder/code_builder.dart';
import 'package:collection/collection.dart';
import 'package:dart_style/dart_style.dart';
import 'package:sealed_countries/sealed_countries.dart';

const String _outputPath = 'lib/src/utils/countries.dart';

void main() async {
  final countries = _buildCountryMap();
  final output = _buildOutput(countries);
  await File(_outputPath).writeAsString(output);

  print('Generated ${countries.length} countries at $_outputPath');
}

Map<String, String> _buildCountryMap() {
  final countriesByCode = {
    for (final country in WorldCountry.list)
      country.codeShort: country.name.common,
  };

  // Sort the entries by name, as that's how users will see them in the UI.
  return Map.fromEntries(
    countriesByCode.entries.sorted((a, b) => a.value.compareTo(b.value)),
  );
}

String _buildOutput(Map<String, String> countries) {
  final field = Field(
    (b) => b
      ..name = 'countryNameByCode'
      ..modifier = FieldModifier.constant
      ..type = refer('Map<String, String>')
      ..docs.add('''
/// 2-letter country codes mapped to their English name and sorted by name.
///
/// The country codes are from the ISO 3166-1 alpha-2 standard,
/// while the English names are their common name, not official names.''')
      ..assignment = literalConstMap(countries).code,
  );

  final library = Library((b) => b.body.add(field));
  final source = library.accept(DartEmitter()).toString();

  const header = '''
// GENERATED CODE - DO NOT MODIFY BY HAND.
//
// Generated by `dart run tool/generate_countries_map.dart`.
''';

  return DartFormatter(
    languageVersion: DartFormatter.latestLanguageVersion,
  ).format('$header\n$source');
}
