// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'blahblahbla',
    appId: '1:123456:web:blahblahbla',
    messagingSenderId: '123456',
    projectId: 'card-game-deadbeef',
    authDomain: 'card-game-deadbeef.firebaseapp.com',
    storageBucket: 'card-game-deadbeef.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'blahblahbla',
    appId: '1:123456:android:blahblahbla',
    messagingSenderId: '123456',
    projectId: 'card-game-deadbeef',
    storageBucket: 'card-game-deadbeef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'blahblahbla',
    appId: '1:123456:ios:blahblahbla',
    messagingSenderId: '123456',
    projectId: 'card-game-deadbeef',
    storageBucket: 'card-game-deadbeef.appspot.com',
    iosBundleId: 'com.example.card',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'blahblahbla',
    appId: '1:123456:ios:blahblahbla',
    messagingSenderId: '123456',
    projectId: 'card-game-deadbeef',
    storageBucket: 'card-game-deadbeef.appspot.com',
    iosBundleId: 'com.example.card.RunnerTests',
  );
}
