include: package:analysis_defaults/analysis.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    # Disabled for now since we have a lot of strings in code currently.
    lines_longer_than_80_chars: false

    avoid_private_typedef_functions: true
    avoid_type_to_string: true
    avoid_void_async: true
    literal_only_boolean_expressions: true
    missing_code_block_language_in_doc_comment: true
    no_runtimeType_toString: true
    no_self_assignments: true
    prefer_const_constructors_in_immutables: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_if_elements_to_conditional_expressions: true

formatter:
  trailing_commas: preserve
