// Copyright 2026, the Flutter authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.

// Generated by `dart run tool/pin_cwebp.dart <version>`,
// run from the `packages/dash_media_convert` directory.

import 'cwebp.dart';

/// The version of libwebp whose prebuilt `cwebp` binary is used.
const String pinnedCwebpVersion = '1.6.0';

/// The prebuilt `cwebp` downloads for [pinnedCwebpVersion],
/// keyed by `'<os>_<arch>'` as returned by [currentCwebpPlatform].
const Map<String, CwebpPin> cwebpPins = {
  'linux_x64': CwebpPin(
    archiveName: 'libwebp-1.6.0-linux-x86-64.tar.gz',
    archiveSha256:
        '1c5ffab71efecefa0e3c23516c3a3a1dccb45cc310ae1095c6f14ae268e38067',
    binarySha256:
        '5ac7ece6bdda1587f3c169ce74ab2734994f9d14e07fc5358208443c1b29edec',
  ),
  'linux_arm64': CwebpPin(
    archiveName: 'libwebp-1.6.0-linux-aarch64.tar.gz',
    archiveSha256:
        '69f5eebe203e0f3942fe37986209a1725741be19c152950a4283b376c95ec798',
    binarySha256:
        'c1cbc3d46a3beb3883359dc9b112d7f5d08ed213a6a5d954f958b6c8baee7fc8',
  ),
  'macos_arm64': CwebpPin(
    archiveName: 'libwebp-1.6.0-mac-arm64.tar.gz',
    archiveSha256:
        'bc6bf84cc70f3f8574fba797d1e4a7dea4feebe9fa4be919f202413ea2b3b8f2',
    binarySha256:
        '07ba910950253f18ca227d085848ff39be530f6ef22005e778cd48d4850734f2',
  ),
  'macos_x64': CwebpPin(
    archiveName: 'libwebp-1.6.0-mac-x86-64.tar.gz',
    archiveSha256:
        'f112dd83b420ab2a4b27d46610d9827ddf4200216023281de378647ecca31c2a',
    binarySha256:
        '5e3017e6106d331a11e6e1684baa6d60d5a48dc30047018bd142756e29014c28',
  ),
  'windows_x64': CwebpPin(
    archiveName: 'libwebp-1.6.0-windows-x64.zip',
    archiveSha256:
        '48886f506b21f62e4661f0f4cbfca19800897c385128e8902542d29a950c93f1',
    binarySha256:
        '6a2f5cb5dce71366353ab1d9caf9c636e039f25703acfce1c148eed346f2f72a',
  ),
};
