// Copyright 2026, the Flutter authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.

import 'dart:convert';
import 'dart:typed_data';

import 'package:build/build.dart';
import 'package:collection/collection.dart';
import 'package:crypto/crypto.dart';
import 'package:glob/glob.dart';

/// Generates a content hash of SCSS source files for CSS cache busting.
///
/// Hashes the SCSS sources rather than the compiled CSS output so that
/// the hash is stable across dev and release builds.
final class StylesHashBuilder implements Builder {
  static final Glob _scssGlob = Glob('lib/styles/**.scss');

  const StylesHashBuilder(this.options);

  final BuilderOptions options;

  @override
  Map<String, List<String>> get buildExtensions => const {
    'web/main.scss': ['lib/src/style_hash.dart'],
  };

  @override
  Future<void> build(BuildStep buildStep) async {
    final String hashString;

    if (options.config['fixed_hash'] == true) {
      hashString = '';
    } else {
      final allBytes = BytesBuilder(copy: false);
      allBytes.add(await buildStep.readAsBytes(buildStep.inputId));

      final scssAssets = await buildStep.findAssets(_scssGlob).toList();

      for (final asset in scssAssets.sortedBy((asset) => asset.path)) {
        allBytes.add(await buildStep.readAsBytes(asset));
      }

      final digest = sha256.convert(allBytes.takeBytes());
      hashString = base64Url.encode(digest.bytes).substring(0, 12);
    }

    await buildStep.writeAsString(
      buildStep.allowedOutputs.single,
      '''
// Copyright 2026, the Flutter authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.

/// Generated by flutter_website|stylesHashBuilder. Do not edit.
///
/// This hash is used to cache bust the CSS file.
/// It is generated from the SCSS source files and
/// is used to ensure that the CSS file is re-generated
/// when the SCSS source files change.
///
/// The hash is generated using the SHA-256 hash function
/// and is encoded using Base64 URL encoding.
library;

// dart format off

/// The generated hash of the SCSS source files.
const generatedStylesHash = '$hashString';
''',
    );
  }
}
