source 'https://rubygems.org'

gem 'activesupport'
gem 'autoprefixer-rails'
gem 'bootstrap'
gem 'font-awesome-sass'
gem 'jekyll', '~> 3.8.4'
gem 'jekyll-assets', group: :jekyll_plugins
gem 'jekyll-toc',
  # :path => '~/git/dart/jekyll-toc'
  :git => 'https://github.com/chalin/jekyll-toc.git',
  :branch => 'master'
gem 'liquid-tag-parser'
gem 'sass'
gem 'sprockets', '~> 4.0.beta' , { require: false }
gem 'uglifier'

# Remaining old infrastructure gems
gem 'html-proofer' # TODO: drop
gem 'rake' # TODO: drop (this seems to be needed only for support of html-proofer)
