source 'https://rubygems.org'
gem 'bootstrap'
gem 'font-awesome-sass'
# Jekyll-assets isn't yet compatible with Jekyll 4. Pin jekyll version.
# https://github.com/envygeeks/jekyll-assets/issues/613
gem 'jekyll', '~> 3'
gem 'jekyll-assets', '~> 3', group: :jekyll_plugins
gem 'jekyll-toc'
gem 'liquid-tag-parser'
gem 'sassc'
# Sprockets > 4.0.beta8 breaks jekyll-assets
# https://github.com/envygeeks/jekyll-assets/issues/589
# So pin the version until the issue is fixed.
# Track progress at https://github.com/envygeeks/jekyll-assets/pull/620
gem 'sprockets', '4.0.beta8'
gem 'uglifier'

# kramdown 2 removed the GitHub Flavored Markdown parser: https://kramdown.gettalong.org/parser/gfm.html
gem 'kramdown-parser-gfm'
