name: ios_devs
description: A new Flutter project.

publish_to: none
version: 1.0.0+1

resolution: workspace
environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.9
  http: ^1.6.0
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
