// Copyright 2026 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Turned off this lint for code clarity,
// as there are a lot of nullable variables.
// ignore_for_file: omit_local_variable_types

import 'dart:async';
import 'dart:io';

import 'package:args/command_runner.dart';
import 'package:csv/csv.dart';
import 'package:http/http.dart' as http;
import 'package:path/path.dart' as path;

import '../utils.dart';

// Do not change
const sheetId = '14lJF-79f7NW6oVkPB0NtshVYMoKMpPtW0u9tIJgb3LY';
const gid = '0';

final class RefreshCujsCommand extends Command<int> {
  @override
  String get description =>
      'Fetches CUJs from a Google Sheet, and updates cuj_table.yml if necessary.';

  @override
  String get name => 'refresh-cujs';

  @override
  FutureOr<int>? run() async {
    await syncSheet();
    return 0;
  }
}

Future<void> syncSheet() async {
  final url = Uri.parse(
    'https://docs.google.com/spreadsheets/d/$sheetId/export?format=csv&gid=$gid',
  );

  print('Fetching CUJ data from Google Sheet...');
  final response = await http.get(url);
  if (response.statusCode == 200) {
    print(response.body.substring(0, 50));

    final codec = Csv(parseHeaders: true);
    final List<CsvRow> records = codec.decodeWithHeaders(response.body);
    final yamlContent = convertToYaml(records);
    final targetPath = path.join(
      repositoryRoot,
      'sites/docs/src/data/cuj_table.yml',
    );
    final targetFile = File(targetPath);
    await targetFile.parent.create(recursive: true);
    await targetFile.writeAsString(yamlContent);

    print('Successfully updated $targetPath');
  } else {
    stderr.writeln(
      'Failed to fetch Google Sheet. HTTP status: ${response.statusCode}',
    );
  }
}

/// Converts parsed CSV maps into clean YAML format for Jaspr Content.
String convertToYaml(List<CsvRow> rows) {
  final buffer = StringBuffer();
  buffer.writeln(
    '# Automatically generated by `dart run dash_site refresh-cujs`.',
  );
  buffer.writeln('# Do not edit directly; update the Google Sheet instead.');
  buffer.writeln();

  for (final row in rows) {
    if (row.toMap() case {
      'Persona': final String p,
      'Goal': final String g,
      'Notes': final String n,
    }) {
      buffer.writeln('- persona: $p');
      buffer.writeln('  goal: |');
      buffer.writeln('    $g');
      buffer.writeln('  note: |');
      buffer.writeln('    $n');
    } else {
      stdout.write('Skipping malformed row: $row');
    }
  }

  return buffer.toString();
}
