name: Dart code

on:
  push:
    branches:
      - main
    paths:
      - '**/*.dart'
      - '**/pubspec.yaml'
      - '**/pubspec.lock'
      - '**/analysis_options.yaml'
      - 'examples/**'
      - 'packages/**'
      - 'tool/dash_site/**'
      - '.github/workflows/dart.yml'
  pull_request:
    branches:
      - main
    paths:
      - '**/*.dart'
      - '**/pubspec.yaml'
      - '**/pubspec.lock'
      - '**/analysis_options.yaml'
      - 'examples/**'
      - 'packages/**'
      - 'tool/dash_site/**'
      - '.github/workflows/dart.yml'
  schedule:
    - cron: '0 0 * * 0'

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  test:
    name: Analyze and test Dart (${{ matrix.name }})
    runs-on: ubuntu-latest
    if: github.repository == 'flutter/website'
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Beta channel"
            branch: beta
            experimental: false
          - name: "Stable channel"
            branch: stable
            experimental: true
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: subosito/flutter-action@e938fdf56512cc96ef2f93601a5a40bde3801046
        with:
          channel: ${{ matrix.branch }}
      - name: Fetch Dart dependencies
        run: dart pub get
        continue-on-error: ${{ matrix.experimental }}
      - name: Check Dart code formatting
        run: dart run dash_site format-dart --check
        continue-on-error: ${{ matrix.experimental }}
      - name: Analyze Dart code
        run: dart run dash_site analyze-dart
        continue-on-error: ${{ matrix.experimental }}
      - name: Run Dart tests
        run: dart run dash_site test-dart
        continue-on-error: ${{ matrix.experimental }}
